### ISSUE TITLE
Set Up Guide?

### ISSUE THREAD

**Issue by leegee** [goodeggs/chai-webdriver#37] opened 2017-09-28 14:38 UTC
When following the setup guide, I get this from the sample:
```
λ node tests\chai.js
C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:2634
        throw error;
        ^

TypeError: checkSizzleExists(...).then(...).then(...).thenCatch is not a function
    at finder (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\node_modules\webdriver-sizzle\lib\webdriver_sizzle.js:60:10)
    at call (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:1066:28)
    at C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:907:19
    at ManagedPromise.invokeCallback_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:1384:14)
    at TaskQueue.execute_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:3092:14)
    at TaskQueue.executeNext_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:3075:27)
    at asyncRun (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:2982:25)
    at C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\promise.js:676:7
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
From: Task: WebDriver.call(function)
    at thenableWebDriverProxy.call (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:901:23)
    at thenableWebDriverProxy.findElementsInternal_ (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:1066:17)
    at thenableWebDriverProxy.findElements (C:\Users\User\AppData\Roaming\npm\node_modules\selenium-webdriver\lib\webdriver.js:1043:19)
    at Function.one.all (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\node_modules\webdriver-sizzle\lib\webdriver_sizzle.js:64:19)
    at assertElementExists (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\lib\index.js:18:16)
    at Proxy.<anonymous> (C:\Users\User\AppData\Roaming\npm\node_modules\chai-webdriver\lib\index.js:90:14)
    at Proxy.methodWrapper (C:\Users\User\AppData\Roaming\npm\node_modules\chai\lib\chai\utils\addMethod.js:57:25)
    at Object.<anonymous> (C:\Users\User\src\izel\tests\chai.js:17:62)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)

```

The file being run is that included in the README.md under the title 'Setup'

**Comment by serhalp** [comment] 2020-06-11 21:33
Duplicate of https://github.com/goodeggs/webdriver-sizzle/issues/8.

**Closed by serhalp** 2020-06-11 21:33 UTC

**Comment by leegee** [comment] 2020-06-12 10:40
I don't think it is a duplicate of a bug resolved in 2014. I saw this in 2017!

**Comment by serhalp** [comment] 2020-06-12 15:14
My bad, I had linked to the wrong issue ([#8 over in webdriver-sizzle](https://github.com/goodeggs/webdriver-sizzle/issues/8), not #8 here!), and I now realize the issue was in a different repo so calling it a duplicate didn't strictly make sense. In any case, the underlying issue was fixed in https://github.com/goodeggs/webdriver-sizzle/issues/8 (and a variation was fixed in https://github.com/goodeggs/chai-webdriver/pull/38).
